### ISSUE TITLE
17. As a user, I want to be able to delete a list

### ISSUE THREAD

**Issue by kweeuhree** [the-collab-lab/tcl-75-smart-shopping-list#60]
# Issue Template

## 🧗🏽 Challenge

- **Audience**: Users of the smart shopping list application who manage shared shopping lists.
- **User goal**: The user wants the ability to delete a shopping list, but how they delete it depends on whether they are the owner of the list.
- **Why it matters**: This feature ensures that users have control over their lists and that the distinction between list owners and non-owners is respected, enhancing the usability and collaborative nature of the app.
- **Broader Objective**: Supporting list management in shared environments while maintaining data integrity across user roles.
- **How we'll accomplish this**: We'll allow list owners to delete lists from both their view and Firebase. Non-owners can only remove the list from their personal view, leaving it available to others and in Firebase.

## ⚡️ Solution

- Describe two distinct deletion flows:
  1. **Owners**: Delete the list from their view and Firebase.
  2. **Non-owners**: Delete only from their own view, leaving the list intact in Firebase for other users.
- Provide a confirmation step before deletion, ensuring users can't accidentally delete lists.
- Open question: How should the app handle cases where a list is deleted by its owner, but other users still need access? (e.g., shared backup or notification flow).
- Links: [Documentation on Firebase deletion](https://firebase.google.com/docs/firestore/manage-data/delete-data).
- Dependencies: No current external dependencies; might require updates in Firebase structure to handle soft-deletions for non-owners.

## 🎨 Designs

The UI should include a confirmation dialog before deleting any list, indicating whether the deletion is local (for non-owners)

## ✅ Acceptance Criteria

- [ ] Owners can permanently delete a list from Firebase and their view.
- [ ] Non-owners can delete a list only from their view, without affecting others or Firebase.
- [ ] Deletion is confirmed through a prompt for all users.
- [ ] Tests to cover both deletion flows for owners and non-owners.
- [ ] ChangeLogs and documentation updated to reflect the new functionality.

## 🚫 Out of Scope

- Handling cases where the owner deletes the list but other users still want to access it (possible future discussion or feature).
- Backend features unrelated to list deletion (e.g., list sharing, editing permissions).

## 📝 Notes

- Consider adding a "soft-delete" for owners, where the list can be archived instead of permanently deleted.
- Ensure Firebase rules are set correctly to distinguish between owners and non-owners.
- Explore the impact of real-time updates in Firebase when an owner deletes a list that others are still using.

**Comment by jendevelops** [comment]
Is this a `soft` or `hard` delete of the list? `Soft` meaning you can restore the deleted list, `hard` meaning permanent delete.

**Comment by deeheber** [comment]
Can anyone with access delete the list or just the owner?
